/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Aplikasi;

import javax.swing.JOptionPane;

/**
 *
 * @author BowoGarra
 */
public class PaymentForm extends javax.swing.JInternalFrame {

    /**
     * Creates new form paymentForm
     */
    public PaymentForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton3 = new javax.swing.JRadioButton();
        radioButton = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        orderNameTxt = new javax.swing.JTextField();
        priceLandTxt = new javax.swing.JTextField();
        areaCombobox = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        t36RadioButton = new javax.swing.JRadioButton();
        t45RadioButton = new javax.swing.JRadioButton();
        t54RadioButton = new javax.swing.JRadioButton();
        buildingPriceTxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        availableLandTxt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        totalPriceTxt = new javax.swing.JTextField();
        DPTxt = new javax.swing.JTextField();
        instalmentAmountTxt = new javax.swing.JTextField();
        ppnTxt = new javax.swing.JTextField();
        instalmentMonthTxt = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        agreementCbx = new javax.swing.JCheckBox();
        processButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        largeLandTxt = new javax.swing.JTextField();

        jRadioButton3.setText("jRadioButton3");

        setTitle("FORM PENJUALAN");

        jLabel1.setText("Nama Pemesan");

        jLabel2.setText("Harga Tanah");

        jLabel3.setText("Area");

        orderNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderNameTxtActionPerformed(evt);
            }
        });

        priceLandTxt.setEditable(false);
        priceLandTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        priceLandTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceLandTxtActionPerformed(evt);
            }
        });

        areaCombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---PILIH---", "KEDATON", "MELATI", "CENDANA" }));
        areaCombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                areaComboboxActionPerformed(evt);
            }
        });

        jLabel5.setText("Harga Bangunan");

        jLabel6.setText("Tipe Rumah");

        radioButton.add(t36RadioButton);
        t36RadioButton.setText("Tipe-36");
        t36RadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t36RadioButtonActionPerformed(evt);
            }
        });

        radioButton.add(t45RadioButton);
        t45RadioButton.setText("Tipe-45");
        t45RadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t45RadioButtonActionPerformed(evt);
            }
        });

        radioButton.add(t54RadioButton);
        t54RadioButton.setText("Tipe-54");
        t54RadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t54RadioButtonActionPerformed(evt);
            }
        });

        buildingPriceTxt.setEditable(false);
        buildingPriceTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        buildingPriceTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buildingPriceTxtActionPerformed(evt);
            }
        });

        jLabel7.setText("Luas Tanah Asli");

        jLabel8.setText("Luas Tanah Tersedia");

        availableLandTxt.setEditable(false);
        availableLandTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        availableLandTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                availableLandTxtActionPerformed(evt);
            }
        });

        jLabel9.setText("Harga");

        jLabel10.setText("DP");

        jLabel11.setText("Lama Cicilan");

        jLabel12.setText("PPn (10%)");

        jLabel13.setText("Cicilan/Bulan");

        totalPriceTxt.setEditable(false);
        totalPriceTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        DPTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        instalmentAmountTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        ppnTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        instalmentMonthTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel14.setText("Bulan");

        agreementCbx.setText("Setuju");
        agreementCbx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agreementCbxActionPerformed(evt);
            }
        });

        processButton.setText("PROSES");
        processButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processButtonActionPerformed(evt);
            }
        });

        saveButton.setText("SIMPAN");

        deleteButton.setText("HAPUS");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        largeLandTxt.setEditable(false);
        largeLandTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        largeLandTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                largeLandTxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(orderNameTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                        .addComponent(priceLandTxt))
                    .addComponent(areaCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(processButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(t45RadioButton)
                                    .addComponent(t54RadioButton)))
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t36RadioButton))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                            .addComponent(buildingPriceTxt)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(availableLandTxt)
                            .addComponent(totalPriceTxt)
                            .addComponent(DPTxt)
                            .addComponent(instalmentAmountTxt)
                            .addComponent(ppnTxt)
                            .addComponent(instalmentMonthTxt)
                            .addComponent(largeLandTxt))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(agreementCbx))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(orderNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(buildingPriceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(priceLandTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(areaCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t36RadioButton)
                    .addComponent(largeLandTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(t45RadioButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(availableLandTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t54RadioButton))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(totalPriceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(DPTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(instalmentAmountTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(ppnTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(instalmentMonthTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(agreementCbx))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(processButton)
                    .addComponent(saveButton)
                    .addComponent(deleteButton))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void areaComboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_areaComboboxActionPerformed
        switch(areaCombobox.getSelectedIndex()){
            case 0:
                priceLandTxt.setText("");
                buildingPriceTxt.setText("");
                radioButton.clearSelection();
                largeLandTxt.setText("");
                availableLandTxt.setText("");
                totalPriceTxt.setText("");
                DPTxt.setText("");
                instalmentAmountTxt.setText("");
                instalmentMonthTxt.setText("");
                ppnTxt.setText("");
                agreementCbx.setSelected(false);
                break;
            
            case 1:
                priceLandTxt.setText("500000");
                buildingPriceTxt.setText("90000000");
                radioButton.clearSelection();
                largeLandTxt.setText("");
                availableLandTxt.setText("");
                totalPriceTxt.setText("");
                DPTxt.setText("");
                instalmentAmountTxt.setText("");
                instalmentMonthTxt.setText("");
                ppnTxt.setText("");
                agreementCbx.setSelected(false);
                break;
                
            case 2:
                priceLandTxt.setText("600000");
                buildingPriceTxt.setText("120000000");
                radioButton.clearSelection();
                largeLandTxt.setText("");
                availableLandTxt.setText("");
                totalPriceTxt.setText("");
                DPTxt.setText("");
                instalmentAmountTxt.setText("");
                instalmentMonthTxt.setText("");
                ppnTxt.setText("");
                agreementCbx.setSelected(false);
                break;
                
            default:
                priceLandTxt.setText("700000");
                buildingPriceTxt.setText("150000000");
                 radioButton.clearSelection();
                largeLandTxt.setText("");
                availableLandTxt.setText("");
                totalPriceTxt.setText("");
                DPTxt.setText("");
                instalmentAmountTxt.setText("");
                instalmentMonthTxt.setText("");
                ppnTxt.setText("");
                agreementCbx.setSelected(false);
                break;    
    }
    }//GEN-LAST:event_areaComboboxActionPerformed

    private void t45RadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t45RadioButtonActionPerformed
         if(areaCombobox.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null,"Pilih area terlebih dahulu");
            radioButton.clearSelection();
        } else {
            largeLandTxt.setText("120");
            availableLandTxt.setText("75");
            long landPrice = Long.parseLong(buildingPriceTxt.getText()),
                    buildingPrice = Long.parseLong(buildingPriceTxt.getText()),
                    availableLand = Long.parseLong(availableLandTxt.getText()),
                    totalPrice;
            totalPrice = (availableLand + landPrice) + buildingPrice;
            totalPriceTxt.setText("" + totalPrice);
            
            DPTxt.setText("");
            ppnTxt.setText("");
            instalmentMonthTxt.setText("");
            instalmentAmountTxt.setText("");
        }
    }//GEN-LAST:event_t45RadioButtonActionPerformed

    private void t54RadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t54RadioButtonActionPerformed
         if(areaCombobox.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null,"Pilih area terlebih dahulu");
            radioButton.clearSelection();
        } else {
            largeLandTxt.setText("140");
            availableLandTxt.setText("86");
            long landPrice = Long.parseLong(buildingPriceTxt.getText()),
                    buildingPrice = Long.parseLong(buildingPriceTxt.getText()),
                    availableLand = Long.parseLong(availableLandTxt.getText()),
                    totalPrice;
            totalPrice = (availableLand + landPrice) + buildingPrice;
            totalPriceTxt.setText("" + totalPrice);
            
            
            DPTxt.setText("");
            ppnTxt.setText("");
            instalmentMonthTxt.setText("");
            instalmentAmountTxt.setText("");
        }
    }//GEN-LAST:event_t54RadioButtonActionPerformed

    private void t36RadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t36RadioButtonActionPerformed
        if(areaCombobox.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null,"Pilih area terlebih dahulu");
            radioButton.clearSelection();
        } else {
            largeLandTxt.setText("90");
            availableLandTxt.setText("54");
            long landPrice = Long.parseLong(buildingPriceTxt.getText()),
                    buildingPrice = Long.parseLong(buildingPriceTxt.getText()),
                    availableLand = Long.parseLong(availableLandTxt.getText()),
                    totalPrice;
            totalPrice = (availableLand + landPrice) + buildingPrice;
            totalPriceTxt.setText("" + totalPrice);
            
            DPTxt.setText("");
            ppnTxt.setText("");
            instalmentMonthTxt.setText("");
            instalmentAmountTxt.setText("");
        }
    }//GEN-LAST:event_t36RadioButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        orderNameTxt.setText("");
        priceLandTxt.setText("");
        buildingPriceTxt.setText("");
        largeLandTxt.setText("");
        availableLandTxt.setText("");
        totalPriceTxt.setText("");
        DPTxt.setText("");
        instalmentAmountTxt.setText("");
        instalmentMonthTxt.setText("");
        ppnTxt.setText("");
        areaCombobox.setSelectedIndex(0);
        radioButton.clearSelection();
        agreementCbx.setSelected(false);
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void processButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processButtonActionPerformed
        if(totalPriceTxt.getText().isEmpty()) {
             JOptionPane.showMessageDialog(null,"Pilihan Belum Lengkap");
        } else if (DPTxt.getText().isEmpty()) {
             JOptionPane.showMessageDialog(null,"Dp Harus Diisi");   
        } else if (instalmentAmountTxt.getText().isEmpty()){
             JOptionPane.showMessageDialog(null,"Isi Jumlah Cicilan  yang diinginkan");
        } else {
             long landPrice = Long.parseLong(buildingPriceTxt.getText()),
                    buildingPrice = Long.parseLong(buildingPriceTxt.getText()),
                    availableLand = Long.parseLong(availableLandTxt.getText()),
                    dp = Long.parseLong(DPTxt.getText()),
                    instalmentAmount = Long.parseLong(instalmentAmountTxt.getText()),
                    totalPrice, ppn, instalmentPerMont;
             totalPrice = (availableLand * landPrice) + buildingPrice;
             ppn = totalPrice * 10/100;
            long instalmentPerMonth = (totalPrice + ppn) / instalmentAmount;
             ppnTxt.setText("" + ppn);
             instalmentMonthTxt.setText("" + instalmentPerMonth);
        }    
    }//GEN-LAST:event_processButtonActionPerformed

    private void agreementCbxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agreementCbxActionPerformed
        if (orderNameTxt.getText().isEmpty()) {
              JOptionPane.showMessageDialog(null,"Nama pemesan harus diisi");
              agreementCbx.setSelected(false);
        } else if (ppnTxt.getText().isEmpty()) {
               JOptionPane.showMessageDialog(null,"Tekan Tombol Proses Terlebih Dahulu ");
               agreementCbx.setSelected(false);
        } else if (agreementCbx.isSelected() == true) {
               JOptionPane.showMessageDialog(null,"Pemesan Menyetujui");
        } else{
               JOptionPane.showMessageDialog(null,"Pesanan Belum Disetujui");
               agreementCbx.setSelected(false);
        }
    }//GEN-LAST:event_agreementCbxActionPerformed

    private void orderNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderNameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_orderNameTxtActionPerformed

    private void priceLandTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceLandTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceLandTxtActionPerformed

    private void buildingPriceTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buildingPriceTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buildingPriceTxtActionPerformed

    private void largeLandTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_largeLandTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_largeLandTxtActionPerformed

    private void availableLandTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_availableLandTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_availableLandTxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DPTxt;
    private javax.swing.JCheckBox agreementCbx;
    private javax.swing.JComboBox<String> areaCombobox;
    private javax.swing.JTextField availableLandTxt;
    private javax.swing.JTextField buildingPriceTxt;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton deleteButton;
    private javax.swing.JTextField instalmentAmountTxt;
    private javax.swing.JTextField instalmentMonthTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JTextField largeLandTxt;
    private javax.swing.JTextField orderNameTxt;
    private javax.swing.JTextField ppnTxt;
    private javax.swing.JTextField priceLandTxt;
    private javax.swing.JButton processButton;
    private javax.swing.ButtonGroup radioButton;
    private javax.swing.JButton saveButton;
    private javax.swing.JRadioButton t36RadioButton;
    private javax.swing.JRadioButton t45RadioButton;
    private javax.swing.JRadioButton t54RadioButton;
    private javax.swing.JTextField totalPriceTxt;
    // End of variables declaration//GEN-END:variables
}
